spring:
  application:
    name: lab-user
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cloudlab
    password: cloud123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
