spring:
  application:
    name: lab-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3307/cloud_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cloudlab
    password: cloud123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6380

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8082

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: 1800
  redis:
    host: localhost
    port: 6380
